[build-system]
requires = ["setuptools>=42", "wheel", "numpy==1.21.4"]
build-backend = "setuptools.build_meta"

[server]
headless = true
port = 10000

[browser]
serverAddress = "0.0.0.0"
serverPort = 10000